<#
.Synopsis 
    Loads a custom SharePoint theme to the SharePoint tenant
.DESCRIPTION
    This command will load a custom theme generated by the Fabric UI theme generator (https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/index.html) into the specified SharePoint tenant
#>

Param(
   [Parameter(Mandatory=$false, HelpMessage="Enter a valid SharePoint tenant")]
   [string]$tenant_name="headforwards",
   [Parameter(Mandatory=$false, HelpMessage="Enter a theme name")]
   [string]$theme_name="Headforwards Corporate Theme"
) 

try{
    $admin_url = "https://{0}-admin.sharepoint.com/" -f $tenant_name

    # Create SharePoint session
    Connect-SPOService -Url $admin_url

    $theme_palette = @{
        "themePrimary" = "#fabb10";
        "themeLighterAlt" = "#fffcf5";
        "themeLighter" = "#fef4d8";
        "themeLight" = "#fdeab6";
        "themeTertiary" = "#fcd66e";
        "themeSecondary" = "#fbc32b";
        "themeDarkAlt" = "#e1a90d";
        "themeDark" = "#be8e0b";
        "themeDarker" = "#8c6908";
        "neutralLighterAlt" = "#faf9f8";
        "neutralLighter" = "#f3f2f1";
        "neutralLight" = "#edebe9";
        "neutralQuaternaryAlt" = "#e1dfdd";
        "neutralQuaternary" = "#d0d0d0";
        "neutralTertiaryAlt" = "#c8c6c4";
        "neutralTertiary" = "#b7b9c9";
        "neutralSecondary" = "#797b92";
        "neutralPrimaryAlt" = "#474960";
        "neutralPrimary" = "#35374b";
        "neutralDark" = "#282938";
        "black" = "#1d1e29";
        "white" = "#ffffff";
        }

    # Load the theme
    Add-SPOTheme -Identity theme_name -Palette $theme_palette -IsInverted $false
}
catch{
    Write-Host "An error occurred:" -ForegroundColor red
    Write-Host $_
}
finally{
    # Close the session
    #Disconnect-SPOService
}

